# Generated by Django 2.2.6 on 2020-01-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(default='new', max_length=255)),
                ('book', models.FileField(upload_to='books/')),
                ('uploaded_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
