# Generated by Django 2.2.6 on 2020-01-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
