# Generated by Django 2.2.6 on 2020-01-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audio',
            field=models.FileField(default='wtf', upload_to='audios/'),
        ),
    ]
