# Generated by Django 2.2.6 on 2020-01-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novelname', models.CharField(max_length=255)),
                ('novelauthor', models.CharField(blank=True, max_length=255)),
                ('novelcategory', models.CharField(default='new', max_length=255)),
                ('novelbook', models.FileField(upload_to='books/')),
                ('novelaudio', models.FileField(default='wtf', upload_to='audios/')),
                ('noveluploaded_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
