# Generated by Django 2.2.6 on 2020-01-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_novel'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsname', models.CharField(max_length=255)),
                ('newsauthor', models.CharField(blank=True, max_length=255)),
                ('newscategory', models.CharField(default='new', max_length=255)),
                ('newsbook', models.FileField(upload_to='books/')),
                ('newsaudio', models.FileField(default='wtf', upload_to='audios/')),
                ('newsuploaded_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
